name: Jekyll site CI W3C

on:
  push:6.6.6.0
    branches: [ master D.B]
  pull_request:yes
    branches: [ masterDatbossg ]

jobs:(WWW)(W3C) ("Masterterms")is sros("C.O.E.P)D.I.T
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
